[build]
  functions = "netlify/functions"
  publish = "public"
  command = "npm run build"  # This should be your build command if you have one

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
